### ISSUE TITLE
contribute prepost_comm.f Nek5000

### ISSUE THREAD

**Issue by maxhutch** [psakievich/NekStuff#1]
It looks like prepost_comm.f is strictly better than prepost.f (more comments and a removed superfluous rzero call).  Could it be contributed to [Nek5000](https://github.com/Nek5000/Nek5000)?

**Comment by psakievich** [comment]
Yes, I suppose so.  The "comm" in prepost_comm.f stands for comments.  I made this file to try and understand/document what was going on in prepost.f.  The extra comments are my own understanding, so they might not be 100% accurate. It might be worth having someone who is more versed in the code review them before putting them in the repo.  

I don't think there are any other major changes as you pointed out. I haven't looked at/dealt with this file in several months. In my local installs I don't actually use this file. While working on prepost_comm.f I decided that any routine I want to modify I would rename and move to another file so I don't accidentally do damage to something in the code. Hence the birth of PhilFunc.f

**Comment by maxhutch** [comment]
I reviewed the comments and they look good; I'd certainly like to put them
in my version, maxhutch/Nek5000.  It'd be better if original authors wrote
in comments, but that doesn't always happen and we should take advantage of
the effort people make to figure out what's going on.

Are you comfortable with forking and opening a pull request?  I'm happy to
just lift them with attribution in the commit log and file header, but
github does a nice job of keeping track of contributors if you do it their
way.

**Comment by psakievich** [comment]
Feel free to fork.  I am happy to share any of these files.

**Comment by maxhutch** [comment]
I meant for you to fork Nek5000/Nek5000 and then copy your prepost_comm.f
to prepost.f in it.

**Comment by psakievich** [comment]
Ah I see. Yes, just catching up.  Your Nek5000 project looks excellent by the way.  You've implemented many of my "wish list" items into it.

**Comment by maxhutch** [comment]
Glad you think so; maybe we should compare wish lists.  Better
time-integration is next on mine.  You also might want to check out
NekBox.  It can't do curved elements, or I'd be looking at more
Rayleigh-Bernard problems.

**Comment by psakievich** [comment]
Okay, I've sent you the pull request.  I've never interacted with anyone else's projects on here before so let me know if there are any problems.  I've really only used git to keep track of my own stuff.  

Yes, I intend to check out both of your projects.  Most of my work with Nek has only been in Rayleigh-Benard since that is what my thesis is going to be centered on.  However, from a computational science standpoint two of my next big items to look at are AMR and dynamic load balancing in an HPC environment.  I think Rayleigh-Benard and multiphase are two ideal test problems for this work.

I am working on setting up a framework for this with finite difference methods for simplicity, but would like to move it over to SEM after I get the FD working.  You're project looks like an ideal candidate since it has dynamic memory capabilities, and the Nek framework I am already familiar with. However, the FD is still a ways out since I can only work on it in my spare time.

**Comment by maxhutch** [comment]
You got it.

You might want to check out this branch, from KTH:
https://github.com/KTH-ExaFlow/Nek5000/tree/nekp4est

**Comment by psakievich** [comment]
Okay thanks.  I heard they were working on some AMR stuff over there.
